export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST';
export const FORGET_PASSWORD_REQUEST_SUCCESS =
  'FORGET_PASSWORD_REQUEST_SUCCESS';
export const FORGET_PASSWORD_REQUEST_FAIL = 'FORGET_PASSWORD_REQUEST_FAIL';
