export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAIL = 'GET_USER_DETAILS_FAIL';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAIL = 'UPDATE_USER_DETAILS_FAIL';

export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
